### ISSUE TITLE
http://localhost:5000/login borkened

### ISSUE THREAD

**Issue by willdayble** [fitzroyacademy/web-app#103]
???

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1676, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 3022, in prepare
    self.fallback(self.request)
  File "/usr/local/lib/python3.7/site-packages/livereload/server.py", line 114, in __call__
    WSGIContainer.environ(request), start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/willdayble/dev/flask-frontend/routes/user.py", line 99, in login
    return render_template('login.html', **data)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/willdayble/dev/flask-frontend/templates/login.html", line 1, in top-level template code
    {% extends "/layout.html" %}
  File "/Users/willdayble/dev/flask-frontend/templates/layout.html", line 63, in top-level template code
    {% include 'partials/_debug_template_vars.html' %}
  File "/Users/willdayble/dev/flask-frontend/templates/partials/_debug_template_vars.html", line 1, in top-level template code
    {% for var in get_vars() %}
  File "app.py", line 57, in get_vars
    methods.append({'name': k, 'dump': datamodels.dump(v)})
  File "/Users/willdayble/dev/flask-frontend/datamodels.py", line 14, in dump
    if isinstance(obj, list) and isinstance(obj[0], Base):
IndexError: list index out of range

```

**Comment by Yuffster** [comment]
This is the server reload stuff, we don't use Tornado in the app itself.

Try restarting `app.py` when this happens.
